### ISSUE TITLE
Clean task does not pass options to del command

### ISSUE THREAD

**Issue by stonecalvin** [vecnatechnologies/quick-sip#15]
Currently the clean task is not passing in options to del (https://www.npmjs.com/package/del). This is an issue for me because I need to delete something in a folder outside of the working directory, which requires the force flag to be passed in. Also the del project has updated to use a promise API, rather than taking in the callback.

**Comment by kentmw** [comment]
Duplicate of issue #9

**Comment by mandragorn** [comment]
This has been fixed by #16
